// components/Layout.js
import Head from 'next/head';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>My Software Manual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        {/* ヘッダー部分 */}
      </header>
      <main>
        {children}
      </main>
      <footer>
        {/* フッター部分 */}
      </footer>
    </>
  );
};

export default Layout;